flyway.url=jdbc:mysql://localhost:3306/liberty_dev?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
flyway.user=admin
flyway.schemas=liberty_dev
flyway.locations=filesystem:./migrations
flyway.cleanDisabled=false
